### ISSUE TITLE
Connection Lost during hijacking the master/slave

### ISSUE THREAD

**Issue by GoulongWang** [RCayre/injectable-firmware#10]
Hi RCayre, 
I encountered some problems when performing the InjectaBLE attack. The following is my environment.
**Attacker**
- Ubuntu 20.04.4 LTS in VMware
- Kernel Version 5.4.0-117-generic
- PCA10059 NRF52840 Dongle

**Master Device**
- FusionRTLS Base Station, BLE 4.1

**Slave Device**
- FusionRTLS Tag, BLE 4.1

I have 2 questions I want to ask for your help.
1. **Connection Lost during hijacking the master/slave**
When performing `Hijacking the Master` or `Hijacking the Slave`, I usually encounter the `Connection Lost` problem. The connection often breaks while sniffing packets. For example, the connection was lost after receiving lots of `Encrypted Packets`. Then the mirage stopped at `[FAIL] Connection lost !` for a very long time.  ![image](https://user-images.githubusercontent.com/23274642/192919066-1ec94de3-7558-4c4f-8365-81504891ff2f.png)
The second example is that the injection was successful but the connection was lost in the end. So `Hijacking the Master` failed.
 ![Master2](https://user-images.githubusercontent.com/23274642/192819722-50220a42-0d95-4141-9674-1d5ed1d2b709.PNG)
The last example is when I performed `Hijacking the slave`, the connection was back after I waited for a few minutes. 
![slave2](https://user-images.githubusercontent.com/23274642/192820463-a0c10bf7-0f32-4e37-a5d5-960087f13c40.PNG)
I want to know the cause of this problem. Why does the mirage (or maybe the dongle) keep disconnecting when attacking? 
2. **Mirage bug: usb.core.USBError: [Errno 110] Operation timed out**
While I was performing both `Hijacking the Master` and `Hijacking the Slave`, the mirage showed the below error message.
- Hijacking the slave
![image](https://user-images.githubusercontent.com/23274642/192922320-81ef69d8-6801-4a4a-b32b-3a000fbac2d2.png)
- Hijacking the master
![image](https://user-images.githubusercontent.com/23274642/192922385-342f1dae-9ff7-4e60-b74b-7ce030f882c0.png)

**Comment by RCayre** [comment]
Hi,
All these issues seems related to the fact that you are trying to sniff and inject packets into an encrypted connection.
The firmware relies on connection update packets to update the channel hopping parameters during sniffing, meaning that if they are encrypted the connection will be lost if the connection is updated. Similarly, you can't inject unencrypted packets into an encrypted connection, it will lead to a connection failure according to the specification.

**Comment by GoulongWang** [comment]
Oh~ I see. Thank you very much
Is it possible to inject packets before encryption procedure ( When the slave responses LL_START_ENC_RSP) ? 
![test](https://user-images.githubusercontent.com/23274642/193449649-e3fe3c36-1b50-468c-a8d9-946fb3c28d5d.PNG)

**Comment by RCayre** [comment]
Theoretically, it is. However, maybe you will have to modify the firmware to make it work (you have to inject the packet soon enough to win the race condition before the encryption starts).
Let me know if you manage to perform this attack, it seems interesting.

**Comment by GoulongWang** [comment]
I got it!  Thanks for your great advice.
I will research this attack recently.
