### ISSUE TITLE
Support for MakerDiary MDK Dongle

### ISSUE THREAD

**Issue by maichai** [RCayre/injectable-firmware#2]
Hi, it should technically be possible to support the MakerDiary Dongle (MDK), which contains the same nRF chip. It is just easier to flash by copying the hex file over to the USB mass storage device the dongle provides.

The hex file probably needs to be different, but you could see how that works here: https://github.com/RoganDawes/LOGITacker
They also support the Nordic dongle AND the MDK dongle.

Would you be willing to port your firmware it to this device?

**Comment by RCayre** [comment]
Hi, 
porting the firmware to this device may be interesting. I'll probably add new protocols and new features soon, and supporting another dongle which is easier to use could be interesting, thanks for the idea !
I just ordered it, i'll try to work on it when I find some time.

**Comment by maichai** [comment]
Awesome! I really like Mirage, although not everthing is working as documented, but it is a great project and I hope it is here to stay.
