### ISSUE TITLE
Provide HEX files as release

### ISSUE THREAD

**Issue by maichai** [RCayre/injectable-firmware#3]
Could you please provide the compiled HEX files for the Nordic dongle (and later possible the MDK dongle) so that not everyone needs to install the toolchain needed to compile them.

**Comment by maichai** [comment]
Hi, are you still around? Or is this repo abandoned?

**Comment by RCayre** [comment]
Hi, the repo is not abandoned :) I have just been very busy these past few weeks, i'm really sorry for the delay.
I just pushed MakerDiary support and pre-compiled hex files, let me know if you find any bugs !
