### ISSUE TITLE
make send does not work for pre-compiled hex files

### ISSUE THREAD

**Issue by maichai** [RCayre/injectable-firmware#5]
- git clone 
- connect NRF dongle
- make send

Error: 
```
Makefile:269: /components/toolchain/gcc/Makefile.common: No such file or directory
make: *** No rule to make target `/components/toolchain/gcc/Makefile.common'.  Stop.
```

Does the Makefile assume that it needs the toolchain, even if the hex files are already there?

**Comment by RCayre** [comment]
Hi, 
Thanks for the issue. Can you git pull and try again ? I added a quick and dirty fix to solve the problem, I will try to find some time to write another Makefile from scratch in the following weeks.
