### ISSUE TITLE
Flashing pre-compiled hex file

### ISSUE THREAD

**Issue by GoulongWang** [RCayre/injectable-firmware#8]
Hi RCayre, 
I flashed the nRF52840 Dongle with pca10059.hex using nRF Programmer app. 
The dongle was detected by my virtual box as below.
![image](https://user-images.githubusercontent.com/23274642/179344533-efde91df-2c1c-456d-a87f-8808570d830a.png)
It seemed correct because the dongle changed its name to "Mirage Toolkit [0001]".

But when I used "lsusb" to show info about the dongle, it didn't display "Mirage Toolkit ButteRFly".
![image](https://user-images.githubusercontent.com/23274642/179344711-b495add3-5267-4b85-b662-1c283ee18d59.png)

Was there something wrong?

**Comment by RCayre** [comment]
Hi, I'm sorry, I'm not familiar with this kind of setup, I can't tell you if this behaviour is normal or not in a virtual machine.
Did you try to run Mirage ? Is the dongle detected and functional ? Can you provide me the output of sudo mirage ble_info INTERFACE=butterfly0 ?

**Comment by GoulongWang** [comment]
Hi RCayre, 
Sorry for the late reply. Here is the screenshot.
![image](https://user-images.githubusercontent.com/23274642/179873798-05bd55e2-2922-44d7-ad34-4ef2008400ee.png)

**Comment by RCayre** [comment]
Hi, everything looks fine on your screenshot, it means that Mirage is able to interact with the dongle.
You should be able to run the various supported modules, the missing name is probably a weird bug linked to your VM setup. 

I close the issue for now, let me know if you encounter any issues.
